[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.13.1",
    "groq>=0.15.0",
    "openai>=1.60.2",
    "streamlit>=1.41.1",
    "twilio>=9.4.3",
]
